project:
  name: "My Anki Project"
  description: "Example project for pdf2anki"
  author: "Your Name"

inputs:
  paths:
    - "samples/*.pdf"
  include_glob: []
  exclude_glob: []

llm:
  provider: openai
  model: "gpt-4o-mini"
  temperature: 0.2
  max_tokens: 1500
  request_timeout_s: 120

generate:
  default_pipeline:
    chunking:
      mode: smart
      max_tokens: 2000
      overlap_tokens: 150
      include_images: true
    prompt: cloze_generation
    note_type: CustomCloze
    params:
      target_card_count: 8
      difficulty: "medium"
    reviewer:
      enabled: false
      min_score: 0.6
      model: "gpt-4o"
      prompt: reviewer_special
    dedup:
      scope: global
      policy: or

  pipelines:
    figure_based:
      chunking:
        mode: figures
        include_images: true
      prompt: figure_explanations
      note_type: Basic
      params: {}
      reviewer:
        enabled: false
      dedup:
        scope: per_pipeline
        policy: or

anki:
  deck_name: "PDF2Anki Generated"
  deck_structure: flat

ids:
  strategy: content_hash
  persistent_index: "workspace/id_index.json"

deduplication:
  policy: or
  index_path: "workspace/dedup_index.json"

rag:
  enabled: false
  index_path: "workspace/rag_index.faiss"

output:
  workspace: "workspace"
  csv_path: "workspace/cards.csv"
  media_path: "workspace/media"
  apkg_path: "workspace/deck.apkg"
  manifest_path: "workspace/manifest.json"

telemetry:
  enabled: true
  log_level: "INFO"
